In [3]:
# ---
# Name: Abdul Azim Abdul Haque
# Track: Data Science
# Task: Task 1 - Iris Flower Classification
# Description: Train a machine learning classification model to identify the species of an iris flower from its physical measurements.
# ---

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Load the Iris dataset
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target
df['species_name'] = df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

# 2. Exploratory Data Analysis (EDA)
print("Dataset Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\nNull Value Check:\n", df.isnull().sum())
print("\nDescriptive Statistics:\n", df.describe())

# 3. Visualizations
plt.figure(figsize=(10, 8))
sns.pairplot(df.drop('species', axis=1), hue='species_name', palette='Set1')
plt.suptitle("Pairplot showing feature distributions by species", y=1.02)
plt.savefig('iris_pairplot.png')
plt.close()

plt.figure(figsize=(12, 6))
for i, feat in enumerate(iris.feature_names):
    plt.subplot(2, 2, i+1)
    sns.boxplot(x='species_name', y=feat, data=df, hue='species_name', palette='Set2', legend=False)
plt.tight_layout()
plt.suptitle("Box plots for each feature across species", y=1.02)
plt.savefig('iris_boxplots.png')
plt.close()

# 4. Feature Selection Discussion
# Petal length and petal width are highly discriminative and show clear separation between species.

# 5. Train/Test Split
X = df[iris.feature_names]
y = df['species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# 6. Train Classifiers
# Model A: Logistic Regression
lr_model = LogisticRegression(max_iter=200)
lr_model.fit(X_train, y_train)
lr_preds = lr_model.predict(X_test)

# Model B: Random Forest Classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)

# 7. Evaluate Models
print("="*40)
print("LOGISTIC REGRESSION ACCURACY:", accuracy_score(y_test, lr_preds))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, lr_preds))
print("\nClassification Report:\n", classification_report(y_test, lr_preds, target_names=iris.target_names))

print("="*40)
print("RANDOM FOREST ACCURACY:", accuracy_score(y_test, rf_preds))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, rf_preds))
print("\nClassification Report:\n", classification_report(y_test, rf_preds, target_names=iris.target_names))

# 8. Declare Best-performing Model
# Both models perform exceptionally well, but Random Forest handles non-linear boundaries natively without feature scaling.


Dataset Shape: (150, 6)

Data Types:
 sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species                int64
species_name          object
dtype: object

Null Value Check:
 sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
species_name         0
dtype: int64

Descriptive Statistics:
        sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.90

LOGISTIC REGRESSION ACCURACY: 0.9666666666666667

Confusion Matrix:
 [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]

Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

RANDOM FOREST ACCURACY: 0.9

Confusion Matrix:
 [[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]

Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.82      0.90      0.86        10
   virginica       0.89      0.80      0.84        10

    accuracy                           0.90        30
    macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        